### ISSUE TITLE
i got this problem can somoene help

### ISSUE THREAD

**Issue by KiyoshiTheBoss** [Koischizo/AI-Vtuber#17]
PS C:\Users\60107\Downloads\AI-Vtuber-main> & "C:/Program Files/Python311/python.exe" c:/Users/60107/Downloads/AI-Vtuber-main/AI-Vtuber-main/run.py
C:\Users\60107\AppData\Roaming\Python\Python311\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to 
ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Unable to open JSON file.

**Comment by KiyoshiTheBoss** [comment]
and i also got this when streaming
PS C:\Users\60107\Desktop\AI-Vtuber-main> python run.py -id oO0RFzUHvSc
C:\Users\60107\AppData\Roaming\Python\Python311\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg 
or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

\Running!



2023-03-31 16:00:08 [Stories maker]- k

Traceback (most recent call last):
  File "C:\Users\60107\Desktop\AI-Vtuber-main\run.py", line 149, in <module>
    read_chat()
  File "C:\Users\60107\Desktop\AI-Vtuber-main\run.py", line 113, in read_chat
    response = llm(message)
               ^^^^^^^^^^^^
  File "C:\Users\60107\Desktop\AI-Vtuber-main\run.py", line 130, in llm
    response = openai.Completion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\60107\AppData\Roaming\Python\Python311\site-packages\openai\api_resources\completion.py", line 25, in 
create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\60107\AppData\Roaming\Python\Python311\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\60107\AppData\Roaming\Python\Python311\site-packages\openai\api_requestor.py", line 226, in request   
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\60107\AppData\Roaming\Python\Python311\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\60107\AppData\Roaming\Python\Python311\site-packages\openai\api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.

**Comment by meet447** [comment]
u need to install ffmpeg and then add its path in your enviornment variable

![image](https://user-images.githubusercontent.com/51074036/232200275-6c08808f-ef65-4934-9acf-0373ebdba86e.png)

**Comment by meet447** [comment]
> ###
> **[meet447](/meet447) ** commented [Apr 15, 2023](#issuecomment-1509632983)

this should fix the issue

**Comment by Sylensar** [comment]
@meet447 I have the same error without the FFMPEG popping up anymore. Im trying to use Twitch instead of Youtube. Could that be it?

**Comment by batgirldee** [comment]
Keepgetting this as well

C:\Users\plane\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
