### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Darelllf** [Koischizo/AI-Vtuber#23]
how to solve this error?

File "run.py", line 84
    url = f'https://api.elevenlabs.io/v1/text-to-speech/{EL.voice}'

**Comment by Darelllf** [comment]
okay thats fix but i get this error


\Running!



2023-04-10 06:12:44 [Nijika-chan Doritos]- Hello


Hello? What can I do for you? If you're here to question my methods of streaming then go ahead, but don't expect me to be friendly about it. I'm not here to please everyone and if that's what you expect from me then think again! Don't waste my time with your complaints or trying to impose your standards on me. It won't fly.
Traceback (most recent call last):
  File "/Users/darelllegoferdanu/Documents/AI-Vtuber/run.py", line 150, in <module>
    read_chat()
  File "/Users/darelllegoferdanu/Documents/AI-Vtuber/run.py", line 116, in read_chat
    Controller_TTS(response)
  File "/Users/darelllegoferdanu/Documents/AI-Vtuber/run.py", line 71, in Controller_TTS
    EL_TTS(message)
  File "/Users/darelllegoferdanu/Documents/AI-Vtuber/run.py", line 100, in EL_TTS
    audio_content = AudioSegment.from_file(io.BytesIO(response.content), format="mp3")
  File "/usr/local/lib/python3.10/site-packages/pydub/audio_segment.py", line 773, in from_file
    raise CouldntDecodeError(
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.28)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/5.1.2_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[cache @ 0x7ff66ea04880] Inner protocol failed to seekback end : -78
    Last message repeated 1 times
[mp3 @ 0x7ff66ea04480] Failed to read frame size: Could not seek to 1239.
[cache @ 0x7ff66ea04880] Statistics, cache hits:2 cache misses:1
cache:pipe:0: Invalid argument

**Comment by meet447** [comment]
i am getting the same issue its related to the mp3 file not getting decoded
