### ISSUE TITLE
I don't know what's going on.

### ISSUE THREAD

**Issue by xayah11106** [Koischizo/AI-Vtuber#30]
I have an issue on  run.py's line 105→chat = pytchat.create(video_id=video_id)
error:
Exception has occurred: TypeError
argument of type 'NoneType' is not iterable
  File "C:\ai gf\desktop-waifu-master\AI-Vtuber-main\run.py", line 105, in read_chat
    chat = pytchat.create(video_id=video_id)
  File "C:\ai gf\desktop-waifu-master\AI-Vtuber-main\run.py", line 149, in <module>
    read_chat()
TypeError: argument of type 'NoneType' is not iterable

"ai gf\desktop-waifu-master"is my folder name don't judge.

**Comment by xayah11106** [comment]
It's saying ,"pychat":Unknown word.And same as the other import

**Comment by xayah11106** [comment]
now I'm having the problem installing pychat.I asked gpt and it said that pychat is for python2.So what should I do?

**Comment by xayah11106** [comment]
Traceback (most recent call last):
  File "C:\Users\HP\aigf\desktop-waifu-master\AI-Vtuber-main\run.py", line 149, in <module>
    read_chat()
  File "C:\Users\HP\aigf\desktop-waifu-master\AI-Vtuber-main\run.py", line 105, in read_chat
    chat = pytchat.create(video_id=video_id)
  File "C:\Users\HP\test\lib\site-packages\pytchat\core\__init__.py", line 6, in create
    _vid = extract_video_id(video_id)
  File "C:\Users\HP\test\lib\site-packages\pytchat\util\__init__.py", line 82, in extract_video_id
    if '[' in url_or_id:
TypeError: argument of type 'NoneType' is not iterable

**Comment by xayah11106** [comment]
what is "video_id" in this code?
