### ISSUE TITLE
I am having issues with the pytchat module someone please help me

### ISSUE THREAD

**Issue by furkanshaikh313** [Koischizo/AI-Vtuber#35]
Traceback (most recent call last):
  File "d:\AI\AI-Vtuber-main\AI-Vtuber-main\run.py", line 167, in <module>
    read_chat()
  File "d:\AI\AI-Vtuber-main\AI-Vtuber-main\run.py", line 106, in read_chat
    chat = pytchat.create(video_id=video_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pytchat\core\__init__.py", line 6, in create
    _vid = extract_video_id(video_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pytchat\util\__init__.py", line 82, in extract_video_id
    if '[' in url_or_id:
       ^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by meet447** [comment]
did you enter the video id?

**Comment by furkanshaikh313** [comment]
yes i did it does work now but the thing is that i want to create a project that is completly free for everyone can you help me make it

**Comment by Fadlay** [comment]
@furkanshaikh313 How do you write the command?
did u write like this?
python run.py --video_id [Your YT-ID Here] --tts_type EL
